name: admin_gl_cashman
version: 1.0.0
publish_to: none
description: ADMIN GL CashMan
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Package
  image_picker: ^1.1.1
  dotted_border: ^2.1.0
  image_cropper: ^7.1.0
  fluttertoast: ^8.2.4
  insta_image_viewer: ^1.0.4
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  persistent_bottom_nav_bar_v2: ^4.2.8

  # Supabase Package
  supabase: ^2.2.4
  supabase_flutter: ^2.5.8

  # Firebase Package
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5

  # Internationalization & Localization
  intl: ^0.19.0

  # Functional Programming
  dartz: ^0.10.1

  # Dependencies Injector
  get_it: ^7.7.0

  # Route
  get: ^4.6.6

  # Value Comparator
  equatable: ^2.0.5

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Information about an application package
  package_info_plus: ^8.0.0

  # Local Data Presistence
  hive_flutter: ^1.1.0

  # Encryption
  crypto: ^3.0.2
  encrypt: ^5.0.1
  envied: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
